// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ports_microservice/internal/adapters/datastore"
	"ports_microservice/internal/adapters/usecasefacades"
	"ports_microservice/internal/drivers/db"
	"ports_microservice/internal/drivers/rest"
	"ports_microservice/internal/usecases"
)

// Injectors from wire.go:

func BuildDIForApp() (*App, error) {
	gormDB := db.NewDB()
	gormDBWrapper := db.NewGormDBWrapper(gormDB)
	portDatastore := datastore.NewPortDataStore(gormDBWrapper)
	createPort := usecases.NewCreatePort(portDatastore)
	getPorts := usecases.NewGetPorts(portDatastore)
	portFacade := usecasefacades.NewPortFacade(createPort, getPorts)
	router := rest.NewRouter(portFacade)
	app := NewApp(router)
	return app, nil
}
